name: flutter_notification_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.4
  workmanager: ^0.5.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/notification.png"

flutter:
  uses-material-design: true
